image: node:10

pages:
  variables:
    PUBLIC_URL: "./"
  script:
    - echo PUBLIC_URL $PUBLIC_URL
    - npm i
    - npm run build --prod
    - node append-ga.js
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
